# Generated by Django 5.1.2 on 2024-11-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpf_sensor_service', '0003_sensorconfig_additionalinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorconfig',
            name='sensorConnectionType',
        ),
        migrations.AddField(
            model_name='sensorconfig',
            name='sensorClassId',
            field=models.UUIDField(default='7711013a-d9f6-4990-9d9b-7222ff98ca9f'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensorconfig',
            name='additionalInformation',
            field=models.TextField(blank=True),
        ),
    ]
