# Generated by Django 5.1.2 on 2024-10-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorConfig',
            fields=[
                ('sensorId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('intervallSeconds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorId', models.CharField(max_length=36)),
                ('measuredAt', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
            ],
        ),
    ]
